// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvdOrgR4s5FAABOObNNlfMVOP6o1IaUY',
    appId: '1:104108982319:web:96368140c509174be106da',
    messagingSenderId: '104108982319',
    projectId: 'messaging-app-95261',
    authDomain: 'messaging-app-95261.firebaseapp.com',
    storageBucket: 'messaging-app-95261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrhrGFeGfrYbTMT89wxQjRIqh_G2H2SI',
    appId: '1:104108982319:android:f7ec9ab8ea673ee9e106da',
    messagingSenderId: '104108982319',
    projectId: 'messaging-app-95261',
    storageBucket: 'messaging-app-95261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-Hn5pxsp-S3CVK4jbZZOw7cFqUNXi00',
    appId: '1:104108982319:ios:08c2bdb4fbf9d611e106da',
    messagingSenderId: '104108982319',
    projectId: 'messaging-app-95261',
    storageBucket: 'messaging-app-95261.appspot.com',
    iosClientId: '104108982319-636ohpukinds0ef204e4t4uu59618qhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-Hn5pxsp-S3CVK4jbZZOw7cFqUNXi00',
    appId: '1:104108982319:ios:08c2bdb4fbf9d611e106da',
    messagingSenderId: '104108982319',
    projectId: 'messaging-app-95261',
    storageBucket: 'messaging-app-95261.appspot.com',
    iosClientId: '104108982319-636ohpukinds0ef204e4t4uu59618qhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );
}
